### ISSUE TITLE
alpine, 2.4.3.3: not stripped, --enable-static does not yield static binaries

### ISSUE THREAD

**Issue by mk-f** [Tripwire/tripwire-open-source#18]
Binaries are not stripped after ``make install``:

```
alpine:~/local/sbin$ file *
siggen:   ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped, with debug_info
tripwire: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped, with debug_info
twadmin:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped, with debug_info
twprint:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped, with debug_info
```

```
alpine:~/local/sbin$ objdump -h tripwire | grep debug
 26 .debug_aranges 000000b0  0000000000000000  0000000000000000  00133270  2**4
 27 .debug_info   0000018b  0000000000000000  0000000000000000  00133320  2**0
 28 .debug_abbrev 000000b7  0000000000000000  0000000000000000  001334ab  2**0
 29 .debug_line   000000ed  0000000000000000  0000000000000000  00133562  2**0
 30 .debug_frame  00000038  0000000000000000  0000000000000000  00133650  2**3
 31 .debug_str    00000171  0000000000000000  0000000000000000  00133688  2**0
 32 .debug_loc    000000d6  0000000000000000  0000000000000000  001337f9  2**0
 33 .debug_ranges 000000a0  0000000000000000  0000000000000000  001338d0  2**4

```

Also ``--enable-static`` will not produce actual static binaries (despite not having any dynamic dependencies):

```
alpine:~/local2/sbin$ file tripwire
tripwire: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped, with debug_info
```
```
alpine:~/local2/sbin$ ldd tripwire
	ldd (0x79ff1aacf000)
```
```
alpine:~/local2/sbin$ scanelf -n tripwire 
 TYPE   NEEDED FILE 
ET_DYN  tripwire 
```
```
alpine:~/local2/sbin$ objdump -h tripwire | head

tripwire:     file format elf64-x86-64

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .gnu.hash     00000160  0000000000000190  0000000000000190  00000190  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .dynsym       000003c0  00000000000002f0  00000000000002f0  000002f0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .dynstr       0000065c  00000000000006b0  00000000000006b0  000006b0  2**0
```

[dynamic.config.log.txt](https://github.com/Tripwire/tripwire-open-source/files/797752/dynamic.config.log.txt)
[static.config.log.txt](https://github.com/Tripwire/tripwire-open-source/files/797753/static.config.log.txt)

I should have noticed this with 2.4.3.3-dev, sorry.

**Comment by brc0x1** [comment]
Interesting...  I tried to repro the enable-static issue with my Alpine 3.3.3 vm, but got the expected a.out binaries, so I spun up a new 3.5.1 vm and I see it there.  To see whether the difference might be due to a newer gcc or ld, I fired up a current Arch vm (with gcc 6.3.1 and ld 2.27), and got a.out binaries there as well.  Also copied an a.out binary from the 3.3.3 vm over to 3.5.1 & ran ldd on it there, on the off-chance it was a difference in ldd behavior, but that showed the 3.3.3 binary was static and the 3.5.1 one wasn't.  Next test was to build Hello World with and without "-static" on both Alpine VMs.  Without "-static", the twexes pulled in a couple of shared libs on both VMs, as expected.  When I specified "-static", I got a static binary on 3.3.3, and a dynamic one w/ no imports on 3.5.1.  Also tried "-static -Wl,-static" on 3.5.1 with identical results.  So I'm not sure what's going here yet.

On a brighter note, I think I understand what's going on with the stripped binary issue, namely that binaries haven't been copied to /usr/local/sbin yet when the strip step happens.  I think I'd expect this to happen with the 'install-strip' make target but not with 'install', or at least that's what the automake-generated targets think they ought to do.

**Comment by mk-f** [comment]
Interesting indeed. Seems like alpine enabled ``--enable-default-pie`` since GCC 6: I am able to produce a static binary which is recognized as static by file and ldd with:
```gcc -no-pie -static -o hello_static hello.c```
BUT i think that the binaries produced without -no-pie are actual static too. Glibc implies -no-pie with -static as it doesn't support PIE with static binaries at all. I'll investigate further.

**Comment by brc0x1** [comment]
I rebuilt with CFLAGS and CXXFLAGS to "-no-pie" and ldd on the resulting exes gave the expected "Not a valid dynamic program".  

Incidentally, there was a long-running issue with static binaries conflicting with uid/gid-to-name resolution that I mitigated in 2.4.3.2.  Glibc's NSS likes to load shared libraries behind the scenes to handle name resolution, even if you have otherwise static binaries.  This would sometimes cause mysterious segfaults during rule runs if the box was trying to resolve names thru LDAP/AD.  So there's a new RESOLVE_IDS_TO_NAMES config option that skips the name resolution step and just reports the numeric IDs, since there was no other way to make NSS & static binaries play nice together.  I gather Alpine's musl libc doesn't have an NSS-like mechanism, so this may not be something you need to worry about, but I figured it was worth mentioning.

**Comment by mk-f** [comment]
Okay, i see. After digging around a bit more, i think that ``file`` and ``ldd`` are just not able to deal with static PIE binaries for now. According to [this](https://gcc.gnu.org/ml/gcc/2015-06/msg00008.html), static PIE binaries are intended so be of type ET_DYN:

> static PIE executables are ET_DYN
format with no PT_INTERP, and are intended to contain only relative
type relocations (no symbol references).

and further down in the same link

> Unfortunately, producing static PIE binaries with GCC is not as simple
as passing -static -pie when linking. The linker arguments I've been
using to test this so far have been:

>     -shared -Wl,-Bstatic -Wl,-Bsymbolic

Which is reflected by [this](http://git.alpinelinux.org/cgit/aports/tree/main/gcc/207-static-pie.patch) alpine-gcc-patch. I talked to some alpine-folks on IRC who confirmed this assumption.

As static with PIE is security-wise more desirable than static w/o PIE, I think it would be better to just leave the CFLAGS for now as they are, change the title of this issue, and wait for alpine to 'fix' ``ldd`` and ``file``?

Thanks for the NSS-hint and sorry for all the fuss.

**Comment by brc0x1** [comment]
Ok, as for the other part of this issue, I just merged a fix as part of the 2.4.3.4 update.  Now binaries will be stripped if you use the install-strip make target.

**Comment by mk-f** [comment]
Mh, its still not working for me, seems like a permission-problem: 
```
Copying files...

/home/vagrant/local/doc/tripwire/COPYING: copied
/home/vagrant/local/sbin/tripwire: copied
/home/vagrant/local/sbin/twadmin: copied
/home/vagrant/local/sbin/twprint: copied
/home/vagrant/local/sbin/siggen: copied
/home/vagrant/local/doc/tripwire/TRADEMARK: copied
/home/vagrant/local/doc/tripwire/policyguide.txt: copied
/home/vagrant/local/etc/twpol-Linux.txt: copied
INSTALL_STRIP_FLAG is set, stripping binaries
strip: unable to copy file '/home/vagrant/local/sbin/siggen'; reason: Permission denied
strip: unable to copy file '/home/vagrant/local/sbin/tripwire'; reason: Permission denied
strip: unable to copy file '/home/vagrant/local/sbin/twadmin'; reason: Permission denied
strip: unable to copy file '/home/vagrant/local/sbin/twprint'; reason: Permission denied
```
``strip`` will not work without u+w, but after copy die permissions are:

```
alpine:~/local/sbin$ ls -l
total 31268
-r-xr-x---    1 vagrant  vagrant    7781656 Mar  7 15:04 siggen
-r-xr-x---    1 vagrant  vagrant    8265744 Mar  7 15:04 tripwire
-r-xr-x---    1 vagrant  vagrant    8026984 Mar  7 15:04 twadmin
-r-xr-x---    1 vagrant  vagrant    7935528 Mar  7 15:04 twprint
```

**Comment by brc0x1** [comment]
Ok, that's easy to fix. I'll roll it into the next update. Mea culpa, apparently I only tested this while sudo'd.

**Comment by brc0x1** [comment]
Ok, 'install-strip' should work properly as a non-root user with the 2.4.3.5 update I merged just now.

**Comment by brc0x1** [comment]
closing as resolved
