### ISSUE TITLE
Object summary is empty since 2.4.3.3 update

### ISSUE THREAD

**Issue by princeofbubbles** [Tripwire/tripwire-open-source#24]
I a running TW on a CentOS 6.8
2.6.32-042stab120.5 #1 SMP Tue Oct 25 22:31:12 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
 with
yum-cron.noarch                    3.2.29-75.el6.centos                @updates

On March 21 there was following automatic update:

#==============================================================
 Package           Arch            Version                  Repository     Size
#==============================================================
Updating:
 tripwire          x86_64          2.4.3.3-1.el6            epel          1.4 M

Ever since this update the Object summary printed after a --check is empty (modified, added, or removed files are not listed any more). The number of violations is correct and the report file shows the violating files. The cfg and pol files have not changed, although there are new versions of the txt files present.

...
Total objects scanned:  41435
Total violations found:  39

#===========================================================
Object Summary:
#===========================================================

#-------------------------------------------------------------------------------
 Section: Unix File System
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
Rule Name: Root config files (/root)
Severity Level: 100
#-------------------------------------------------------------------------------

#===========================================================
Error Report:
#===========================================================

No Errors

#-------------------------------------------------------------------------------

**Comment by didier13150** [comment]
Hi,
I'm not a tripwire dev, but the package maintainer in epel and fedora. I've just send push query about tripwire 2.4.3.4 to stable repository this morning.
You already can try this version in testing repo or wait a little, mirrors are not sync yet.
You can check this bug status here: https://bugzilla.redhat.com/show_bug.cgi?id=1435181 and check when it will be closed (aka new version pushed on stable repo)

**Comment by brc0x1** [comment]
Hi, the issue you're seeing is something I broke in 2.4.3.3 (see https://github.com/Tripwire/tripwire-open-source/issues/19 for details ), and it's fixed in 2.4.3.4 & later.

**Comment by didier13150** [comment]
tripwire-2.4.3.4-1.el6 has been pushed to the Fedora EPEL 6 stable repository. If problems still persist, please make note of it in this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1435181

**Comment by brc0x1** [comment]
Great, glad to hear it!

**Comment by brc0x1** [comment]
closing as resolved
